channels:
- conda-forge
dependencies:
- python=3.11.3
- pip<=23.1.2
- pip:
  - mlflow==3.1.1
  - cloudpickle==2.2.1
  - lz4==4.3.2
  - numpy==1.23.5
  - pandas==2.2.3
  - pathlib==1.0.1
  - psutil==5.9.0
  - scikit-learn==1.6.1
  - scipy==1.15.2
name: mlflow-env
